import { addDays, set } from "date-fns";

import { DEFAULT_SETTINGS } from "@/lib/planner/constants";
import type {
  EventRecord,
  MilestoneRecord,
  ProjectRecord,
  TaskBlockRecord,
  TaskChecklistItemRecord,
  TaskDependencyRecord,
  TaskRecord,
  TaskTagRecord,
  WorkspaceSnapshot,
} from "@/lib/planner/types";

function isoAtOffset(days: number, hours: number, minutes = 0) {
  const now = new Date();
  const date = addDays(now, days);

  return set(date, {
    hours,
    minutes,
    seconds: 0,
    milliseconds: 0,
  }).toISOString();
}

export function createSeedSnapshot(userId = "demo-user"): WorkspaceSnapshot {
  const createdAt = new Date().toISOString();
  const areas = [
    { id: "area-work", userId, name: "Work", color: "#0f766e", createdAt, updatedAt: createdAt },
    {
      id: "area-health",
      userId,
      name: "Health",
      color: "#b45309",
      createdAt,
      updatedAt: createdAt,
    },
  ];
  const projects: ProjectRecord[] = [
    {
      id: "project-launch",
      userId,
      areaId: "area-work",
      name: "Planner MVP",
      color: "#0f766e",
      status: "active",
      deadlineAt: addDays(new Date(), 10).toISOString(),
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "project-wellness",
      userId,
      areaId: "area-health",
      name: "Training Block",
      color: "#b45309",
      status: "active",
      deadlineAt: addDays(new Date(), 30).toISOString(),
      createdAt,
      updatedAt: createdAt,
    },
  ];
  const milestones: MilestoneRecord[] = [
    {
      id: "milestone-discovery",
      userId,
      projectId: "project-launch",
      name: "Discovery",
      description: "Lock product framing, navigation, and first-run assumptions.",
      startDate: isoAtOffset(-3, 9),
      deadline: isoAtOffset(4, 18),
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "milestone-build",
      userId,
      projectId: "project-launch",
      name: "Build sprint",
      description: "Ship the planning flow, project views, and settings QA.",
      startDate: isoAtOffset(5, 9),
      deadline: isoAtOffset(14, 18),
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "milestone-foundation",
      userId,
      projectId: "project-wellness",
      name: "Foundation block",
      description: "Build consistency and baseline strength sessions.",
      startDate: isoAtOffset(-5, 7),
      deadline: isoAtOffset(6, 20),
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "milestone-progression",
      userId,
      projectId: "project-wellness",
      name: "Progression cycle",
      description: "Increase load and refine weekly recovery targets.",
      startDate: isoAtOffset(7, 7),
      deadline: isoAtOffset(24, 20),
      createdAt,
      updatedAt: createdAt,
    },
  ];
  const tags = [
    { id: "tag-focus", userId, name: "Focus", color: "#1d4ed8", createdAt, updatedAt: createdAt },
    { id: "tag-admin", userId, name: "Admin", color: "#6d28d9", createdAt, updatedAt: createdAt },
    { id: "tag-errand", userId, name: "Errand", color: "#9a3412", createdAt, updatedAt: createdAt },
  ];
  const tasks: TaskRecord[] = [
    {
      id: "task-outline",
      userId,
      title: "Outline the planner onboarding",
      notes: "Decide how new users set work hours, timezone, and default planning horizon.",
      priority: "high",
      estimatedMinutes: 90,
      dueAt: isoAtOffset(1, 11),
      preferredTimeBand: "morning",
      preferredWindowStart: "08:30",
      preferredWindowEnd: "11:30",
      status: "todo",
      availability: "ready",
      completedAt: null,
      areaId: "area-work",
      projectId: "project-launch",
      milestoneId: "milestone-build",
      recurrence: null,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "task-review",
      userId,
      title: "Review overdue follow-ups",
      notes: "Clear anything that slipped from yesterday and either reschedule or archive it.",
      priority: "critical",
      estimatedMinutes: 45,
      dueAt: isoAtOffset(-1, 16),
      preferredTimeBand: "anytime",
      preferredWindowStart: null,
      preferredWindowEnd: null,
      status: "todo",
      availability: "ready",
      completedAt: null,
      areaId: "area-work",
      projectId: "project-launch",
      milestoneId: null,
      recurrence: null,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "task-gym",
      userId,
      title: "Strength session",
      notes: "Upper-body block. Keep it at 60 minutes.",
      priority: "medium",
      estimatedMinutes: 60,
      dueAt: isoAtOffset(0, 19),
      preferredTimeBand: "evening",
      preferredWindowStart: "17:30",
      preferredWindowEnd: "20:30",
      status: "in_progress",
      availability: "ready",
      completedAt: null,
      areaId: "area-health",
      projectId: "project-wellness",
      milestoneId: "milestone-foundation",
      recurrence: null,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "task-plan",
      userId,
      title: "Daily planning reset",
      notes: "Close loops, choose top three, and rebalance the afternoon.",
      priority: "medium",
      estimatedMinutes: 30,
      dueAt: isoAtOffset(0, 8),
      preferredTimeBand: "morning",
      preferredWindowStart: "08:00",
      preferredWindowEnd: "09:00",
      status: "todo",
      availability: "ready",
      completedAt: null,
      areaId: "area-work",
      projectId: "project-launch",
      milestoneId: "milestone-discovery",
      recurrence: {
        frequency: "daily",
      },
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "task-kickoff",
      userId,
      title: "Approve planner kickoff brief",
      notes: "Confirm scope, launch goals, and success measures with the core team.",
      priority: "high",
      estimatedMinutes: 75,
      dueAt: isoAtOffset(-2, 13),
      preferredTimeBand: "morning",
      preferredWindowStart: "09:00",
      preferredWindowEnd: "12:00",
      status: "done",
      availability: "ready",
      completedAt: isoAtOffset(-2, 11),
      areaId: "area-work",
      projectId: "project-launch",
      milestoneId: "milestone-discovery",
      recurrence: null,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "task-qa",
      userId,
      title: "Draft release QA checklist",
      notes: "List regression flows for quick add, themes, queue, and modal interactions.",
      priority: "medium",
      estimatedMinutes: 60,
      dueAt: isoAtOffset(8, 15),
      preferredTimeBand: "afternoon",
      preferredWindowStart: "13:00",
      preferredWindowEnd: "16:30",
      status: "todo",
      availability: "ready",
      completedAt: null,
      areaId: "area-work",
      projectId: "project-launch",
      milestoneId: "milestone-build",
      recurrence: null,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "task-recovery",
      userId,
      title: "Plan recovery weekend",
      notes: "Set low-intensity sessions and mobility work around the next progression push.",
      priority: "low",
      estimatedMinutes: 40,
      dueAt: isoAtOffset(11, 18),
      preferredTimeBand: "evening",
      preferredWindowStart: "17:00",
      preferredWindowEnd: "20:00",
      status: "done",
      availability: "ready",
      completedAt: isoAtOffset(0, 18),
      areaId: "area-health",
      projectId: "project-wellness",
      milestoneId: "milestone-foundation",
      recurrence: null,
      createdAt,
      updatedAt: createdAt,
    },
  ];
  const taskBlocks: TaskBlockRecord[] = [
    {
      id: "block-plan",
      userId,
      taskId: "task-plan",
      startsAt: isoAtOffset(0, 8),
      endsAt: isoAtOffset(0, 8, 30),
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "block-outline",
      userId,
      taskId: "task-outline",
      startsAt: isoAtOffset(0, 10),
      endsAt: isoAtOffset(0, 11, 30),
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "block-kickoff",
      userId,
      taskId: "task-kickoff",
      startsAt: isoAtOffset(-2, 10),
      endsAt: isoAtOffset(-2, 11, 15),
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "block-gym",
      userId,
      taskId: "task-gym",
      startsAt: isoAtOffset(0, 18),
      endsAt: isoAtOffset(0, 19),
      createdAt,
      updatedAt: createdAt,
    },
  ];
  const events: EventRecord[] = [
    {
      id: "event-standup",
      userId,
      title: "Product standup",
      notes: "Daily sync with engineering and design.",
      location: "Zoom",
      startsAt: isoAtOffset(0, 9),
      endsAt: isoAtOffset(0, 9, 30),
      recurrence: {
        frequency: "weekdays",
      },
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "event-review",
      userId,
      title: "Project review",
      notes: "Lock scope for the first release.",
      location: "Studio",
      startsAt: isoAtOffset(1, 14),
      endsAt: isoAtOffset(1, 15),
      recurrence: null,
      createdAt,
      updatedAt: createdAt,
    },
  ];
  const checklistItems: TaskChecklistItemRecord[] = [
    {
      id: "check-1",
      taskId: "task-outline",
      label: "Define setup steps",
      completed: true,
      sortOrder: 0,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "check-2",
      taskId: "task-outline",
      label: "Write first-run copy",
      completed: false,
      sortOrder: 1,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "check-3",
      taskId: "task-qa",
      label: "Cover task modal workflow",
      completed: false,
      sortOrder: 0,
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "check-4",
      taskId: "task-qa",
      label: "Cover project planning Gantt interactions",
      completed: false,
      sortOrder: 1,
      createdAt,
      updatedAt: createdAt,
    },
  ];
  const taskTags: TaskTagRecord[] = [
    { taskId: "task-outline", tagId: "tag-focus" },
    { taskId: "task-review", tagId: "tag-admin" },
    { taskId: "task-gym", tagId: "tag-errand" },
    { taskId: "task-qa", tagId: "tag-admin" },
    { taskId: "task-kickoff", tagId: "tag-focus" },
  ];
  const taskDependencies: TaskDependencyRecord[] = [
    {
      taskId: "task-qa",
      dependsOnTaskId: "task-outline",
      createdAt,
    },
  ];

  return {
    user: {
      id: userId,
      email: "planner@example.com",
      fullName: "Inflara User",
      createdAt,
      updatedAt: createdAt,
    },
    settings: {
      ...DEFAULT_SETTINGS,
      userId,
      createdAt,
      updatedAt: createdAt,
    },
    areas,
    projects,
    milestones,
    tags,
    tasks: tasks.map((task) => ({ ...task })),
    taskBlocks,
    events,
    checklistItems,
    taskTags,
    taskDependencies,
    apiAccessTokens: [],
    agentRunners: [],
    projectAgentLinks: [],
    agentRuns: [],
    agentRunEvents: [],
  };
}
